name: graphql_schema
version: 0.0.0
description: An implementation of GraphQL's type system in Dart.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/graphql_schema
environment:
  sdk: ">=1.19.0"
dependencies:
  graphql_parser: ^1.0.0
dev_dependencies:
  test: ^0.12.0